---
title: "Statistics"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    theme: spacelab
    toc: yes
    toc_float: yes
---
# Correlate Taxa with modulus
```{r corr_taxa_modulus}
rm(list = ls())
source("./code/R/00_setup.R")
source("./code/R/01_load_data.R")
source("./code/R/02_process_ps.R")
source("./code/R/03_subset.R")
source("./code/R/04_bias_correct.R")

# For correlation
size_midpoint <- c(1.125, 1.7, 2.4, 3.4, 4.5)

p_threshold <- 0.15

# Choose DA taxa
write2excel = FALSE
ancom_taxa <- get_ancom_taxa(ancom_fname, ps, p_threshold, rel_ab_cutoff, write2excel, fname_excel)
DA_taxa <- ancom_taxa$high_ab 
# Common taxa (ANCOM & ALDEx)
# DA_taxa2 <- get_common_taxa(ancom_fname, aldex_fname, p_threshold, effect_threshold)

rel_bc <- get_bc_abund(ancom_fname) %>%
  filter(OTU %in% DA_taxa) %>%
  group_by(OTU, size.name) %>%
  summarise(mean_ab = mean(bc_abund), sd_ab = sd(bc_abund), .groups = "drop") %>%
  dplyr::select(OTU, size.name, mean_ab) %>%
  pivot_wider(
    names_from = size.name,
    values_from = mean_ab
  ) %>%
  column_to_rownames("OTU") %>%
  as.matrix()

corr_mod <- map_dfr(1:nrow(rel_bc), function(i) {
  res <- cor.test(rel_bc[i, ], modulus$G1.avg, method = "spearman")
  tibble(
    OTU = rownames(rel_bc)[i],
    # correlation coefficient (+ increasing, - decreasing)
    estimate = res$estimate, 
    p.value = res$p.value
  ) 
}) %>%
  arrange(p.value)

corr_mod_adj <- corr_mod %>%
  mutate(p.adj = p.adjust(p.value, method = "BH")) %>%
  filter(p.adj < p_threshold)

print(corr_mod_adj)
```

# Correlate Taxa with EPS
```{r corr_taxa_eps}
corr_tb <- map_dfr(1:nrow(rel_bc), function(i) {
  res <- cor.test(rel_bc[i, ], eps$TB.avg, method = "spearman")
  tibble(
    OTU = rownames(rel_bc)[i],
    # correlation coefficient (+ increasing, - decreasing)
    estimate = res$estimate,
    p.value = res$p.value
  )
}) %>%
  arrange(p.value)

# Adjust p-values for multiple comparisons
corr_tb_adj <- corr_tb %>%
  mutate(p.adj = p.adjust(p.value, method = "BH")) 

print(corr_tb_adj)

corr_lb <- map_dfr(1:nrow(rel_bc), function(i) {
  res <- cor.test(rel_bc[i, ], eps$LB.avg, method = "spearman")
  tibble(
    OTU = rownames(rel_bc)[i],
    # correlation coefficient (+ increasing, - decreasing)
    estimate = res$estimate,
    p.value = res$p.value
  )
}) %>%
  arrange(p.value)

# Adjust p-values for multiple comparisons
corr_lb_adj <- corr_lb %>%
  mutate(p.adj = p.adjust(p.value, method = "BH"))

print(corr_lb_adj)
```

# Correlate modulus and EPS and size
```{r corr}
merged <- as.data.frame(modulus) %>%
  left_join(eps, join_by(size.name)) %>%
  mutate(size.midpoint = size_midpoint)

# Named list of variable pairs
var_pairs <- list(
  TB_mod   = c("TB.avg", "G1.avg"),
  LB_mod   = c("LB.avg", "G1.avg"),
  size_G1 = c("size.midpoint", "G1.avg"),
  size_G2 = c("size.midpoint", "G2.avg"),
  size_TB  = c("size.midpoint", "TB.avg"),
  size_LB  = c("size.midpoint", "LB.avg")
)

# One-liner to get estimates and p-values
results <- map_dfr(var_pairs, ~ cor.test(merged[[.x[1]]], merged[[.x[2]]], method = "spearman") %>%
                     broom::tidy(), .id = "comparison") %>%
  dplyr::select(comparison, estimate, p.value) %>%
  arrange(p.value)

# Adjust p-values for multiple comparisons
results_adj <- results %>%
  mutate(p.adj = p.adjust(p.value, method = "BH")) 

print(results_adj)

```